site_name: indl

repo_url: https://github.com/SachsLab/indl/

theme:
  name: "material"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocstrings
  - mknotebooks:
      execute: false
      enable_default_jupyter_cell_styling: false
#      preamble: "mkdocs_preamble.py"

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
